import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { KnowledgeAwareShadowPipeline } from "../src/bil/knowledge-aware-shadow-pipeline";
import { parseBilModule } from "../src/bil/bil.parser";
import { BilRegistry } from "../src/bil/bil.registry";
import { ShadowBiktingPipeline } from "../src/bil/shadow-bikting-pipeline";
import { CapabilityRegistry } from "../src/capabilities/capability.registry";
import { createDefaultRelationshipTypeRegistry } from "../src/core/relationship.registry";
import { CanonicalExecutionKernel } from "../src/execution/canonical-execution-kernel";
import { CanonicalProviderInvoker } from "../src/execution/provider-invoker";
import { normalizeKnowledgeContext } from "../src/knowledge/knowledge-context";
import { resolveKnowledge } from "../src/knowledge/knowledge.resolver";
import { InMemoryDocumentKnowledgeAdapter, KnowledgeModuleSourceAdapter, KnowledgeRetriever, StaticStructuredKnowledgeAdapter } from "../src/knowledge/knowledge-retriever";
import { KnowledgeRequirement } from "../src/knowledge/knowledge-requirement.types";
import { KnowledgeSourceRegistry } from "../src/knowledge/knowledge-source.registry";
import { KnowledgeArtifact, KnowledgeSource } from "../src/knowledge/knowledge-source.types";
import { adaptLegacyProvider } from "../src/providers/legacyCapabilityAdapter";
import { CapabilityProviderRegistry } from "../src/providers/provider.registry";
import { createDefaultRegistries } from "../src/bikting/core/registry/createDefaultRegistries.js";
import { calculatorTool } from "../src/bikting/core/tools/deterministic/mathTools.js";

const paths = ["bil/modules/core/calculation.bil.json", "bil/modules/core/code-generation.bil.json", "bil/modules/core/dataset-analysis.bil.json", "bil/modules/core/vision-interpretation.bil.json", "bil/modules/science/electric-motor.bil.json", "bil/modules/science/force.bil.json", "bil/modules/science/force-relationship.bil.json", "bil/modules/workflows/equation-plot.bil.json", "bil/modules/workflows/force-plot.bil.json"];
function environment() { const bilRegistry = new BilRegistry(); paths.forEach((path) => bilRegistry.register(parseBilModule(readFileSync(path, "utf8")))); const capabilityRegistry = new CapabilityRegistry(), providerRegistry = new CapabilityProviderRegistry(), ids = new Set<string>(); const active = createDefaultRegistries(); for (const adapter of [...active.tools.list(), ...active.models.list()]) { const adapted = adaptLegacyProvider(adapter); providerRegistry.register(adapted.provider); for (const capability of adapted.capabilities) if (!ids.has(capability.id)) { capabilityRegistry.registerCapability(capability); ids.add(capability.id); } } return { bilRegistry, capabilityRegistry, providerRegistry, relationshipTypeRegistry: createDefaultRelationshipTypeRegistry() }; }
const stableRequirement: KnowledgeRequirement = { id: "knowledge-test", domain: "physics", concepts: ["force"], freshness: "stable", required: true };
function source(id: string, changes: Partial<KnowledgeSource> = {}): KnowledgeSource { return { id, name: id, type: "structured", domains: ["physics"], conceptIds: ["force"], freshness: ["stable"], availability: "available", retrievalKind: "static", authority: { level: 1 }, ...changes }; }
function concept(id: string) { return { id, kind: "concept" as const, name: id, content: {} }; }

test("knowledge requirement and source registry contracts cover freshness, optionality, availability, and deterministic discovery", () => { const registry = new KnowledgeSourceRegistry(); registry.register(source("z", { availability: "unavailable" })); const registered = registry.register(source("a")); assert.equal(Object.isFrozen(registered), true); assert.deepEqual(registry.list().map(({ id }) => id), ["a", "z"]); assert.deepEqual(registry.query({ domain: "physics", conceptIds: ["force"] }).map(({ id }) => id), ["a", "z"]); assert.throws(() => registry.register(source("a")), /already registered/); assert.equal(stableRequirement.freshness, "stable"); assert.equal(stableRequirement.required, true); assert.equal(({ ...stableRequirement, required: false }).required, false); assert.equal(({ ...stableRequirement, freshness: "live" as const }).freshness, "live"); });

test("resolution preserves multiple candidates and distinguishes unavailable, blocked, freshness mismatch, and unresolved", () => { const registry = new KnowledgeSourceRegistry(); registry.register(source("a")); registry.register(source("b")); registry.register(source("off", { availability: "unavailable" })); registry.register(source("private", { accessRequirementIds: ["access.private"] })); const resolution = resolveKnowledge([stableRequirement], registry); assert.deepEqual(resolution.entries[0].eligibleSourceIds, ["a", "b"]); assert.deepEqual(resolution.entries[0].unavailableSourceIds, ["off"]); assert.deepEqual(resolution.entries[0].accessBlockedSourceIds, ["private"]); const live = resolveKnowledge([{ ...stableRequirement, freshness: "live" }], registry); assert.deepEqual(live.unresolvedRequirementIds, [stableRequirement.id]); assert.match(live.entries[0].reason, /No source satisfies/); });

test("local structured, document, and KnowledgeModule adapters retrieve inert artifacts with zero remote activity", async () => { const registry = new KnowledgeSourceRegistry(), retriever = new KnowledgeRetriever(); const sources = [source("structured"), source("document", { type: "document", retrievalKind: "document" }), source("module", { type: "graph", retrievalKind: "knowledge_module" })]; sources.forEach((item) => registry.register(item)); retriever.register(new StaticStructuredKnowledgeAdapter("structured", { contentType: "structured", concepts: [concept("force")], facts: [{ subject: "force", value: "interaction" }] })); retriever.register(new InMemoryDocumentKnowledgeAdapter("document", { title: "Local", text: "Force is an interaction.", concepts: [concept("force")] })); retriever.register(new KnowledgeModuleSourceAdapter("module", { id: "module.local", name: "Local", domain: "physics", concepts: [concept("force")], relationships: [] })); let count = 0; for (const item of sources) { const artifacts = await retriever.retrieve({ retrievalId: `r-${item.id}`, requirement: stableRequirement, source: item }); count += artifacts.length; assert.equal(artifacts[0].sourceId, item.id); assert.ok(artifacts[0].provenance.length); } assert.equal(count, 3); await assert.rejects(() => new KnowledgeRetriever().retrieve({ retrievalId: "remote", requirement: stableRequirement, source: source("remote", { retrievalKind: "future_remote", type: "api" }) }), /Remote knowledge retrieval is disabled/); });

test("normalization deduplicates a task graph, preserves provenance, and records conflicts without choosing a winner", () => { const types = createDefaultRelationshipTypeRegistry(); const resolution = resolveKnowledge([stableRequirement], (() => { const registry = new KnowledgeSourceRegistry(); registry.register(source("a")); registry.register(source("b")); return registry; })()); const artifacts: KnowledgeArtifact[] = ["a", "b"].map((id, index) => ({ id: `artifact-${id}`, retrievalId: `retrieval-${id}`, sourceId: id, requirementId: stableRequirement.id, contentType: "structured", concepts: [concept("force"), concept("motion")], facts: [{ subject: "force", predicate: "magnitude", value: index ? 110 : 100 }], relationships: [{ id: "force-causes-motion", type: "causes", from: "force", to: "motion" }], evidence: [{ type: "test", value: id }], freshness: "stable", retrievedAt: "1970-01-01T00:00:00.000Z", provenance: [{ sourceId: id, requirementId: stableRequirement.id }] })); const context = normalizeKnowledgeContext(resolution, artifacts, types); assert.equal(context.concepts.length, 2); assert.equal(context.relationships.length, 1); assert.equal(context.conflicts.length, 1); assert.equal(context.conflicts[0].candidates.length, 2); assert.equal(context.provenance.length, 2); assert.equal(context.graph.findRelated("force", "causes")[0].id, "motion"); assert.equal(context.graph.isSealed(), true); assert.equal(Object.isFrozen(context), true); });

function motorKnowledge() { const sources = new KnowledgeSourceRegistry(), retriever = new KnowledgeRetriever(); const concepts = ["current", "magnetic_field", "current_carrying_conductor", "interaction", "force", "torque", "rotation"].map(concept); const relationships = [{ id: "current-produces-field", type: "produces", from: "current", to: "magnetic_field" }, { id: "field-interacts-conductor", type: "interacts_with", from: "magnetic_field", to: "current_carrying_conductor" }, { id: "field-produces-interaction", type: "produces", from: "magnetic_field", to: "interaction" }, { id: "interaction-produces-force", type: "produces", from: "interaction", to: "force" }, { id: "force-produces-torque", type: "produces", from: "force", to: "torque" }, { id: "torque-causes-rotation", type: "causes", from: "torque", to: "rotation" }]; sources.register({ id: "local.motor.physics", name: "Motor physics", type: "structured", domains: ["physics"], conceptIds: concepts.map(({ id }) => id), relationshipTypes: ["produces", "causes", "interacts_with"], freshness: ["stable"], authority: { level: 1 }, provenanceCharacteristics: { traceable: true, evidence: true }, availability: "available", retrievalKind: "static", provenance: { citation: "local structured motor fixture" } }); retriever.register(new StaticStructuredKnowledgeAdapter("local.motor.physics", { contentType: "graph", concepts, relationships, facts: [{ subject: "electric_motor", predicate: "rotation_cause", value: "electromagnetic torque" }], evidence: [{ type: "structured", value: "local motor physics" }] })); return { sources, retriever }; }

test("electric-motor BIL requirement resolves into deterministic local task-specific knowledge before planning", async () => { const env = environment(), knowledge = motorKnowledge(); const result = await new KnowledgeAwareShadowPipeline().run({ projectId: "motor", intent: { rawInput: "Explain why an electric motor rotates.", goal: "Explain motor rotation", actions: ["explain"], objects: ["electric_motor"], desiredOutputs: ["explanation", "visual", "voice"], context: { domain: "physics" } }, bilRegistry: env.bilRegistry, capabilityRegistry: env.capabilityRegistry, relationshipTypeRegistry: env.relationshipTypeRegistry, knowledgeSources: knowledge.sources, retriever: knowledge.retriever }); assert.deepEqual(result.bilContext.knowledgeRequirements.map(({ declaration }) => declaration.id), ["knowledge-electric-motor"]); assert.deepEqual(result.knowledgeResolution.entries[0].eligibleSourceIds, ["local.motor.physics"]); assert.equal(result.knowledgeContext.unresolvedRequirementIds.length, 0); assert.equal(result.knowledgeContext.graph.findRelated("torque", "causes")[0].id, "rotation"); assert.equal(result.plan.knowledgeContextId, result.knowledgeContext.id); assert.deepEqual(result.events.map(({ type }) => type), ["knowledge_resolution_started", "knowledge_resolution_completed", "knowledge_retrieval_started", "knowledge_retrieval_completed", "knowledge_context_created"]); const again = await new KnowledgeAwareShadowPipeline().run({ projectId: "motor", intent: { rawInput: "Explain why an electric motor rotates.", goal: "Explain motor rotation", actions: ["explain"], objects: ["electric_motor"], desiredOutputs: ["explanation", "visual", "voice"], context: { domain: "physics" } }, bilRegistry: env.bilRegistry, capabilityRegistry: env.capabilityRegistry, relationshipTypeRegistry: env.relationshipTypeRegistry, knowledgeSources: knowledge.sources, retriever: knowledge.retriever }); assert.equal(result.knowledgeContext.id, again.knowledgeContext.id); assert.deepEqual(result.events, again.events); });

test("calculation declares no knowledge, retrieves nothing, and still executes to 6000", async () => { const env = environment(), sources = new KnowledgeSourceRegistry(), retriever = new KnowledgeRetriever(); let retrievals = 0; sources.register({ id: "unused", name: "Unused", type: "structured", domains: ["mathematics"], conceptIds: [], freshness: ["stable"], availability: "available", retrievalKind: "static" }); retriever.register({ sourceId: "unused", async retrieve() { retrievals++; return []; } }); const intent = { rawInput: "Calculate 125 * 48.", goal: "Calculate", actions: ["calculate"], desiredOutputs: ["numeric_result", "equation"], context: { domain: "mathematics", expression: "125 * 48" } }; const knowledge = await new KnowledgeAwareShadowPipeline().run({ projectId: "calculation", intent, bilRegistry: env.bilRegistry, capabilityRegistry: env.capabilityRegistry, relationshipTypeRegistry: env.relationshipTypeRegistry, knowledgeSources: sources, retriever }); assert.equal(knowledge.bilContext.knowledgeRequirements.length, 0); assert.equal(knowledge.artifacts.length, 0); assert.equal(retrievals, 0); const shadow = new ShadowBiktingPipeline().run({ projectId: "calculation", intent, bilRegistry: env.bilRegistry, capabilityRegistry: env.capabilityRegistry, providerRegistry: env.providerRegistry, relationshipTypeRegistry: env.relationshipTypeRegistry }); const invoker = new CanonicalProviderInvoker(); invoker.register({ providerId: "math.calculator", capabilityIds: ["math.calculate"], async invoke({ input }) { return calculatorTool.execute(input); } }); const executed = await new CanonicalExecutionKernel(env.capabilityRegistry, env.providerRegistry, invoker).execute({ preparedPlan: shadow.preparedPlan!, projectId: "calculation" }); assert.equal((executed.outputs["step-math-calculate"] as { numericResult: number }).numericResult, 6000); });

test("private sources are discoverable but never retrieved without authority", async () => { const registry = new KnowledgeSourceRegistry(); registry.register(source("private", { accessRequirementIds: ["private.read"] })); const blocked = resolveKnowledge([stableRequirement], registry); assert.deepEqual(blocked.entries[0].accessBlockedSourceIds, ["private"]); let retrievals = 0; const retriever = new KnowledgeRetriever(); retriever.register({ sourceId: "private", async retrieve() { retrievals++; return []; } }); assert.equal(retrievals, 0); const allowed = resolveKnowledge([stableRequirement], registry, { grants: [{ id: "grant", requirementId: "private.read", providerId: "private", status: "granted", grantedAt: "1970-01-01T00:00:00.000Z" }] }); assert.deepEqual(allowed.entries[0].eligibleSourceIds, ["private"]); await retriever.retrieve({ retrievalId: "authorized", requirement: stableRequirement, source: registry.get("private")! }); assert.equal(retrievals, 1); });
