import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { ShadowBiktingPipeline } from "../src/bil/shadow-bikting-pipeline";
import { parseBilModule } from "../src/bil/bil.parser";
import { BilRegistry } from "../src/bil/bil.registry";
import { CapabilityRegistry } from "../src/capabilities/capability.registry";
import { evaluatePlanAuthorization } from "../src/core/authorization";
import { createDefaultRelationshipTypeRegistry } from "../src/core/relationship.registry";
import { CanonicalExecutionKernel } from "../src/execution/canonical-execution-kernel";
import { resolveStepInputBindings } from "../src/execution/input-binding.resolver";
import { CanonicalProviderInvoker } from "../src/execution/provider-invoker";
import { projectCanonicalExecutionState } from "../src/execution/execution-state";
import { ExecutionPlan } from "../src/planning/plan.types";
import { prepareExecutionPlan, withProviderSelections } from "../src/planning/prepared-plan";
import { adaptLegacyProvider } from "../src/providers/legacyCapabilityAdapter";
import { CapabilityProviderRegistry } from "../src/providers/provider.registry";
import { resolvePlanProviders } from "../src/providers/provider.resolver";
import { selectPreparedPlanProviders, StableFirstAuthorizedProviderPolicy } from "../src/providers/provider-selection.policy";
import { createDefaultRegistries } from "../src/bikting/core/registry/createDefaultRegistries.js";
import { calculatorTool } from "../src/bikting/core/tools/deterministic/mathTools.js";

const modulePaths = ["bil/modules/core/calculation.bil.json", "bil/modules/core/code-generation.bil.json", "bil/modules/core/dataset-analysis.bil.json", "bil/modules/core/vision-interpretation.bil.json", "bil/modules/science/electric-motor.bil.json", "bil/modules/science/force.bil.json", "bil/modules/science/force-relationship.bil.json", "bil/modules/workflows/equation-plot.bil.json", "bil/modules/workflows/force-plot.bil.json"];
function environment() { const bilRegistry = new BilRegistry(); modulePaths.forEach((path) => bilRegistry.register(parseBilModule(readFileSync(path, "utf8")))); const capabilityRegistry = new CapabilityRegistry(), providerRegistry = new CapabilityProviderRegistry(), ids = new Set<string>(); const active = createDefaultRegistries(); for (const adapter of [...active.tools.list(), ...active.models.list()]) { const adapted = adaptLegacyProvider(adapter); providerRegistry.register(adapted.provider); for (const capability of adapted.capabilities) if (!ids.has(capability.id)) { capabilityRegistry.registerCapability(capability); ids.add(capability.id); } } return { bilRegistry, capabilityRegistry, providerRegistry, relationshipTypeRegistry: createDefaultRelationshipTypeRegistry() }; }
function calculation() { const env = environment(); const shadow = new ShadowBiktingPipeline().run({ projectId: "calculation", intent: { rawInput: "Calculate 125 * 48.", goal: "Calculate", actions: ["calculate"], desiredOutputs: ["numeric_result", "equation"], context: { domain: "mathematics", expression: "125 * 48" } }, ...env }); assert.equal(shadow.status, "ready"); return { env, shadow }; }
function calculatorInvoker(counter: { value: number }, result?: unknown) { const invoker = new CanonicalProviderInvoker(); invoker.register({ providerId: "math.calculator", capabilityIds: ["math.calculate"], async invoke({ input }) { counter.value += 1; return result ?? calculatorTool.execute(input); } }); return invoker; }

test("binding resolver handles all sources defensively and rejects unsafe or missing paths", () => {
  const step = { id: "b", action: "test", status: "pending" as const, inputBindings: [{ target: "intent", source: { type: "intent" as const, path: ["context", "value"] } }, { target: "context", source: { type: "context" as const, path: ["project"] } }, { target: "literal", source: { type: "literal" as const, value: { stable: true } } }, { target: "upstream", source: { type: "step_output" as const, stepId: "a", path: ["values", "0"] } }] };
  const resolved = resolveStepInputBindings(step, { intent: { context: { value: 7 } }, context: { project: "p" }, stepOutputs: new Map([["a", { values: [11] }]]) }); assert.equal(resolved.status, "resolved"); if (resolved.status === "resolved") { assert.deepEqual(resolved.inputs, { intent: 7, context: "p", literal: { stable: true }, upstream: 11 }); assert.equal(Object.isFrozen(resolved.inputs), true); }
  const unsafe = resolveStepInputBindings({ ...step, inputBindings: [{ target: "x", source: { type: "intent", path: ["__proto__"] } }] }, { intent: {}, stepOutputs: new Map() }); assert.equal(unsafe.status, "unresolved"); if (unsafe.status === "unresolved") assert.equal(unsafe.failures[0].code, "unsafe_path");
  const missing = resolveStepInputBindings({ ...step, inputBindings: [{ target: "x", source: { type: "context", path: ["missing"] } }] }, { context: {}, stepOutputs: new Map() }); assert.equal(missing.status, "unresolved");
});

test("arithmetic executes through the complete canonical architecture and verifies 6000", async () => {
  const { env, shadow } = calculation(); const calls = { value: 0 }; const result = await new CanonicalExecutionKernel(env.capabilityRegistry, env.providerRegistry, calculatorInvoker(calls)).execute({ preparedPlan: shadow.preparedPlan!, projectId: "calculation" });
  assert.equal(result.status, "completed"); assert.equal(calls.value, 1); assert.equal((result.outputs["step-math-calculate"] as { numericResult: number }).numericResult, 6000); assert.equal(result.observations.length, 1); assert.equal(result.verificationResults[0].status, "PASS"); assert.equal(result.stepResults[0].status, "verified"); assert.equal(result.attempts[0].capabilityId, "math.calculate"); assert.equal(result.state.status, "completed");
  assert.deepEqual(result.events.map(({ type }) => type), ["execution_started", "step_ready", "input_bindings_resolved", "step_started", "provider_invoked", "provider_completed", "observation_recorded", "verification_started", "verification_completed", "step_succeeded", "execution_completed"]); assert.deepEqual(projectCanonicalExecutionState(result.events), result.state);
});

function recordingPlan(options: { failFirst?: boolean; verification?: string } = {}) {
  const capabilities = new CapabilityRegistry(); capabilities.registerCapability({ id: "test.produce", kind: "capability", name: "Produce", operations: ["produce"], inputs: [], outputs: [{ name: "values", type: "numeric_data" }] }); capabilities.registerCapability({ id: "test.consume", kind: "capability", name: "Consume", operations: ["consume"], inputs: [{ name: "dataset", type: "numeric_data", required: true }], outputs: [{ name: "count", type: "numeric_result" }] });
  const providers = new CapabilityProviderRegistry(); providers.register({ id: "recorder.a", name: "A", capabilityIds: ["test.produce"], executorKind: "custom", availability: "available" }); providers.register({ id: "recorder.b", name: "B", capabilityIds: ["test.consume"], executorKind: "custom", availability: "available" });
  const plan: ExecutionPlan = { id: "recording-plan", goal: "record", status: "ready", requiredCapabilityIds: ["test.produce", "test.consume"], steps: [{ id: "a", action: "produce", capabilityId: "test.produce", dependsOn: [], expectedInputs: [], expectedOutputs: [{ name: "values", type: "numeric_data" }], executionRequirements: [], verificationRequirements: [], outputRequirements: [], provenance: [{ sourceType: "engine" }], status: "pending" }, { id: "b", action: "consume", capabilityId: "test.consume", dependsOn: ["a"], inputBindings: [{ target: "dataset", source: { type: "step_output", stepId: "a", path: ["values"] } }], expectedInputs: [{ name: "dataset", type: "numeric_data", required: true }], expectedOutputs: [{ name: "count", type: "numeric_result" }], executionRequirements: [], verificationRequirements: options.verification ? [{ id: "verify", method: options.verification, required: true }] : [], outputRequirements: [], provenance: [{ sourceType: "engine" }], status: "pending" }] };
  const resolution = resolvePlanProviders(plan, capabilities, providers); const authorization = evaluatePlanAuthorization(resolution, []); let prepared = prepareExecutionPlan(plan, resolution, authorization); prepared = withProviderSelections(prepared, selectPreparedPlanProviders(prepared, new StableFirstAuthorizedProviderPolicy())); const calls: Array<{ provider: string; input: Record<string, unknown> }> = []; const invoker = new CanonicalProviderInvoker(); invoker.register({ providerId: "recorder.a", capabilityIds: ["test.produce"], async invoke({ input }) { calls.push({ provider: "a", input: structuredClone(input) }); if (options.failFirst) throw new Error("recorded failure"); return { values: [1, 2, 3] }; } }); invoker.register({ providerId: "recorder.b", capabilityIds: ["test.consume"], async invoke({ input }) { calls.push({ provider: "b", input: structuredClone(input) }); return { numericResult: (input.dataset as unknown[]).length }; } }); return { capabilities, providers, prepared, invoker, calls };
}

test("multi-step recording providers execute once in dependency order with resolved upstream data", async () => { const setup = recordingPlan(); const result = await new CanonicalExecutionKernel(setup.capabilities, setup.providers, setup.invoker).execute({ preparedPlan: setup.prepared, projectId: "recording" }); assert.equal(result.status, "completed"); assert.deepEqual(setup.calls.map(({ provider }) => provider), ["a", "b"]); assert.deepEqual(setup.calls[1].input, { dataset: [1, 2, 3] }); assert.equal(result.observations.length, 2); assert.ok(result.events.findIndex(({ type, taskId }) => type === "provider_completed" && taskId === "a") < result.events.findIndex(({ type, taskId }) => type === "provider_invoked" && taskId === "b")); });

test("provider failure produces a failure observation and blocks downstream execution", async () => { const setup = recordingPlan({ failFirst: true }); const result = await new CanonicalExecutionKernel(setup.capabilities, setup.providers, setup.invoker).execute({ preparedPlan: setup.prepared, projectId: "failure" }); assert.equal(result.status, "failed"); assert.deepEqual(setup.calls.map(({ provider }) => provider), ["a"]); assert.equal(result.stepResults[1].status, "blocked"); assert.equal((result.observations[0].observedState as { success: boolean }).success, false); assert.ok(result.observations[0].metadata?.provenance); });

test("blocked, unavailable, unauthorized, invalid-selection, and unresolved-input steps never invoke providers", async () => {
  const { env, shadow } = calculation();
  for (const mutate of [
    (prepared: typeof shadow.preparedPlan) => ({ ...prepared!, status: "blocked" as const }),
    (prepared: typeof shadow.preparedPlan) => ({ ...prepared!, providerSelections: [{ stepId: "step-math-calculate", providerId: "missing", status: "selected" as const, reason: "test" }] }),
    (prepared: typeof shadow.preparedPlan) => ({ ...prepared!, authorization: { ...prepared!.authorization, steps: prepared!.authorization.steps.map((step) => ({ ...step, status: "blocked" as const, authorizedProviderIds: [] })), blockedStepIds: ["step-math-calculate"] } }),
    (prepared: typeof shadow.preparedPlan) => ({ ...prepared!, plan: { ...prepared!.plan, originatingIntent: { ...prepared!.plan.originatingIntent!, context: { domain: "mathematics" } } } }),
  ]) { const calls = { value: 0 }; const result = await new CanonicalExecutionKernel(env.capabilityRegistry, env.providerRegistry, calculatorInvoker(calls)).execute({ preparedPlan: mutate(shadow.preparedPlan), projectId: "blocked" }); assert.equal(calls.value, 0); assert.equal(result.status, "blocked"); }
  const unavailableProviders = new CapabilityProviderRegistry(); unavailableProviders.register({ ...env.providerRegistry.get("math.calculator")!, availability: "unavailable" }); const calls = { value: 0 }; const unavailable = await new CanonicalExecutionKernel(env.capabilityRegistry, unavailableProviders, calculatorInvoker(calls)).execute({ preparedPlan: shadow.preparedPlan!, projectId: "unavailable" }); assert.equal(calls.value, 0); assert.equal(unavailable.status, "blocked");
});

test("verification failures and unsupported methods never silently pass", async () => { const { env, shadow } = calculation(); const wrongCalls = { value: 0 }; const failed = await new CanonicalExecutionKernel(env.capabilityRegistry, env.providerRegistry, calculatorInvoker(wrongCalls, { numericResult: 1 })).execute({ preparedPlan: shadow.preparedPlan!, projectId: "wrong" }); assert.equal(failed.status, "failed"); assert.equal(failed.verificationResults[0].status, "FAIL"); const setup = recordingPlan({ verification: "future_method" }); const unsupported = await new CanonicalExecutionKernel(setup.capabilities, setup.providers, setup.invoker).execute({ preparedPlan: setup.prepared, projectId: "unsupported" }); assert.equal(unsupported.status, "failed"); assert.equal(unsupported.verificationResults[0].status, "UNSUPPORTED"); });

test("deterministic execution replays to identical semantic output and state", async () => { const { env, shadow } = calculation(); const run = async () => new CanonicalExecutionKernel(env.capabilityRegistry, env.providerRegistry, calculatorInvoker({ value: 0 })).execute({ preparedPlan: shadow.preparedPlan!, projectId: "determinism" }); const left = await run(), right = await run(); assert.deepEqual(left.stepResults, right.stepResults); assert.deepEqual(left.observations, right.observations); assert.deepEqual(left.verificationResults, right.verificationResults); assert.deepEqual(left.events, right.events); assert.deepEqual(left.state, right.state); });
