import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { BilCompiler } from "../src/bil/bil.compiler";
import { parseBilModule } from "../src/bil/bil.parser";
import { BilRegistry } from "../src/bil/bil.registry";
import { resolveBil } from "../src/bil/bil.resolver";
import { CapabilityRegistry } from "../src/capabilities/capability.registry";
import { createDefaultRelationshipTypeRegistry } from "../src/core/relationship.registry";
import { KnowledgeDiscoveryEngine } from "../src/knowledge/knowledge-discovery.engine";
import { resolveKnowledge } from "../src/knowledge/knowledge.resolver";
import { KnowledgeRetriever, StaticStructuredKnowledgeAdapter } from "../src/knowledge/knowledge-retriever";
import { KnowledgeRequirement } from "../src/knowledge/knowledge-requirement.types";
import { KnowledgeSourceRegistry } from "../src/knowledge/knowledge-source.registry";
import { KnowledgeSource } from "../src/knowledge/knowledge-source.types";
import { StructuredIntentConceptExtractor } from "../src/knowledge/semantic-concepts";
import { adaptLegacyProvider } from "../src/providers/legacyCapabilityAdapter";
import { createDefaultRegistries } from "../src/bikting/core/registry/createDefaultRegistries.js";

const modulePaths = ["bil/modules/core/calculation.bil.json", "bil/modules/science/electric-motor.bil.json"];
function environment() { const bil = new BilRegistry(); modulePaths.forEach((path) => bil.register(parseBilModule(readFileSync(path, "utf8")))); const capabilities = new CapabilityRegistry(), ids = new Set<string>(); const active = createDefaultRegistries(); for (const adapter of [...active.tools.list(), ...active.models.list()]) { const adapted = adaptLegacyProvider(adapter); for (const capability of adapted.capabilities) if (!ids.has(capability.id)) { capabilities.registerCapability(capability); ids.add(capability.id); } } return { bil, capabilities, types: createDefaultRelationshipTypeRegistry() }; }
function compile(intent: { rawInput: string; goal: string; actions?: string[]; objects?: string[]; desiredOutputs?: string[]; context?: Record<string, unknown> }) { const env = environment(); const resolution = resolveBil(env.bil, { intents: intent.actions ?? [], concepts: intent.objects, requestedOutputs: intent.desiredOutputs, context: intent.context, availableCapabilityIds: env.capabilities.list().map(({ id }) => id) }); const context = new BilCompiler().compile({ intent, resolution, modules: resolution.selectedModuleIds.map((id) => env.bil.get(id)!), bilRegistry: env.bil, capabilityRegistry: env.capabilities, relationshipTypeRegistry: env.types }); return { ...env, context }; }
function concept(id: string) { return { id, kind: "concept" as const, name: id, content: {} }; }
function addEdge(registry: KnowledgeSourceRegistry, retriever: KnowledgeRetriever, id: string, from: string, type: string, to: string, options: Partial<KnowledgeSource> = {}) { const source: KnowledgeSource = { id, name: id, type: "structured", domains: ["test", "physics", "economics"], conceptIds: [from, to], relationshipTypes: [type], freshness: ["stable"], availability: "available", retrievalKind: "static", provenanceCharacteristics: { traceable: true, evidence: true }, ...options }; registry.register(source); retriever.register(new StaticStructuredKnowledgeAdapter(id, { contentType: "graph", concepts: [concept(from), concept(to)], relationships: [{ id: `${id}-edge`, type, from, to }], evidence: [{ type: "fixture", value: id }] })); }
function chainIntent(from: string, to: string, domain = "test") { return { rawInput: `Establish ${from} to ${to}`, goal: "Discover relationship", actions: ["explain"], objects: [from, to], context: { domain, relationshipGoals: [{ from, to, acceptableTypes: ["causes", "produces", "interacts_with"], match: "path", evidenceRequired: true }] } }; }

test("semantic extraction uses canonical structured concepts rather than literal question tokens", () => { const set = new StructuredIntentConceptExtractor().extract({ rawInput: "What happens to businesses when fuel prices rise?", goal: "Understand effects", actions: ["explain"], objects: ["business", "fuel_price", "price_increase"], context: { semanticConcepts: [{ id: "change", kind: "event" }] } }); assert.deepEqual(set.concepts.map(({ id }) => id), ["business", "causal_effect", "change", "fuel_price", "price_increase"]); assert.ok(!set.concepts.some(({ id }) => ["what", "when", "to"].includes(id))); });

test("knowledge resolution models collective partial coverage and remaining gaps", () => { const registry = new KnowledgeSourceRegistry(), retriever = new KnowledgeRetriever(); addEdge(registry, retriever, "s1", "a", "causes", "b"); addEdge(registry, retriever, "s2", "b", "causes", "c"); const requirement: KnowledgeRequirement = { id: "abc", domain: "test", concepts: ["a", "b", "c"], relationshipTypes: ["causes"], freshness: "stable", required: true, requireProvenance: true, evidenceRequired: true }; const resolution = resolveKnowledge([requirement], registry); assert.deepEqual(resolution.entries[0].eligibleSourceIds, ["s1", "s2"]); assert.deepEqual(resolution.entries[0].contributions.map(({ sourceId, coveredConceptIds }) => [sourceId, coveredConceptIds]), [["s1", ["a", "b"]], ["s2", ["b", "c"]]]); assert.deepEqual(resolution.entries[0].uncoveredConceptIds, []); assert.equal(resolution.entries[0].unresolved, false); });

test("electric motor graph is assembled collectively from five independent sources", async () => { const compiled = compile({ rawInput: "Explain why an electric motor rotates.", goal: "Explain", actions: ["explain"], objects: ["electric_motor"], desiredOutputs: ["explanation", "visual", "voice"], context: { domain: "physics", relationshipGoals: [{ from: "current", to: "rotation", acceptableTypes: ["produces", "causes", "interacts_with"], match: "path", evidenceRequired: true }] } }); const registry = new KnowledgeSourceRegistry(), retriever = new KnowledgeRetriever(); addEdge(registry, retriever, "motor-a", "current", "produces", "magnetic_field", { domains: ["physics"] }); const sourceB: KnowledgeSource = { id: "motor-b", name: "motor-b", type: "structured", domains: ["physics"], conceptIds: ["magnetic_field", "current_carrying_conductor", "interaction"], relationshipTypes: ["interacts_with", "produces"], freshness: ["stable"], availability: "available", retrievalKind: "static", provenanceCharacteristics: { traceable: true, evidence: true } }; registry.register(sourceB); retriever.register(new StaticStructuredKnowledgeAdapter("motor-b", { contentType: "graph", concepts: sourceB.conceptIds!.map(concept), relationships: [{ id: "motor-b-1", type: "interacts_with", from: "magnetic_field", to: "current_carrying_conductor" }, { id: "motor-b-2", type: "produces", from: "current_carrying_conductor", to: "interaction" }], evidence: [{ type: "fixture", value: "motor-b" }] })); addEdge(registry, retriever, "motor-c", "interaction", "produces", "force", { domains: ["physics"] }); addEdge(registry, retriever, "motor-d", "force", "produces", "torque", { domains: ["physics"] }); addEdge(registry, retriever, "motor-e", "torque", "causes", "rotation", { domains: ["physics"] }); const result = await new KnowledgeDiscoveryEngine().discover({ projectId: "motor", intent: compiled.context.intent, bilContext: compiled.context, sourceRegistry: registry, retriever, relationshipTypeRegistry: compiled.types, budget: { maxRounds: 6 } }); assert.equal(result.stopReason, "sufficient"); assert.equal(result.sufficiency.status, "sufficient"); assert.deepEqual(result.rounds.map(({ selectedSourceIds }) => selectedSourceIds), [["motor-a"], ["motor-b"], ["motor-c"], ["motor-d"], ["motor-e"]]); assert.equal(result.knowledgeContext.graph.findRelated("torque", "causes")[0].id, "rotation"); assert.ok(result.knowledgeContext.relationships.every(({ metadata }) => metadata?.knowledgeEvidence)); });

test("missing motor edge produces a gap and follow-up requirement without fabrication", async () => { const compiled = compile({ rawInput: "Explain motor", goal: "Explain", actions: ["explain"], objects: ["electric_motor"], desiredOutputs: ["explanation", "visual", "voice"], context: { domain: "physics", relationshipGoals: [{ from: "current", to: "rotation", acceptableTypes: ["produces", "causes"], match: "path", evidenceRequired: true }] } }); const registry = new KnowledgeSourceRegistry(), retriever = new KnowledgeRetriever(); addEdge(registry, retriever, "a", "current", "produces", "magnetic_field", { domains: ["physics"] }); addEdge(registry, retriever, "b", "magnetic_field", "produces", "force", { domains: ["physics"] }); addEdge(registry, retriever, "c", "force", "produces", "torque", { domains: ["physics"] }); const result = await new KnowledgeDiscoveryEngine().discover({ projectId: "missing", intent: compiled.context.intent, bilContext: compiled.context, sourceRegistry: registry, retriever, relationshipTypeRegistry: compiled.types }); assert.ok(["no_eligible_source", "no_progress"].includes(result.stopReason)); assert.ok(result.gaps.some(({ type, frontierConceptId }) => type === "unresolved_relationship" && frontierConceptId === "torque")); assert.ok(result.generatedRequirements.some(({ concepts }) => concepts.includes("torque") && concepts.includes("rotation"))); assert.equal(result.knowledgeContext.graph.getRelationship("torque-causes-rotation"), undefined); assert.notEqual(result.sufficiency.status, "sufficient"); });

test("bounded recursive discovery expands A to B to C to D over three rounds", async () => { const compiled = compile(chainIntent("a", "d")); const registry = new KnowledgeSourceRegistry(), retriever = new KnowledgeRetriever(); addEdge(registry, retriever, "round-a", "a", "causes", "b"); addEdge(registry, retriever, "round-b", "b", "causes", "c"); addEdge(registry, retriever, "round-c", "c", "causes", "d"); const engine = new KnowledgeDiscoveryEngine(); const result = await engine.discover({ projectId: "chain", intent: compiled.context.intent, bilContext: compiled.context, sourceRegistry: registry, retriever, relationshipTypeRegistry: compiled.types }); assert.equal(result.stopReason, "sufficient", JSON.stringify({ rounds: result.rounds, gaps: result.gaps, sufficiency: result.sufficiency })); assert.deepEqual(result.rounds.map(({ selectedSourceIds }) => selectedSourceIds), [["round-a"], ["round-b"], ["round-c"]]); assert.deepEqual(result.knowledgeContext.graph.findRelated("c", "causes").map(({ id }) => id), ["d"]); const bounded = await engine.discover({ projectId: "chain", intent: compiled.context.intent, bilContext: compiled.context, sourceRegistry: registry, retriever, relationshipTypeRegistry: compiled.types, budget: { maxRounds: 2 } }); assert.equal(bounded.stopReason, "budget_exhausted"); assert.equal(bounded.rounds.length, 2); assert.equal(bounded.knowledgeContext.graph.getEntity("d"), undefined); });

test("business causal discovery expands meaningful concepts through a generic multi-hop chain", async () => { const intent = { rawInput: "What happens to businesses when fuel prices rise?", goal: "Understand business effects", actions: ["explain"], objects: ["business", "fuel_price", "price_increase"], context: { domain: "economics", semanticConcepts: [{ id: "change", kind: "event" }], relationshipGoals: [{ from: "fuel_price", to: "profit_margin", acceptableTypes: ["causes"], match: "path", evidenceRequired: true }] } }; const compiled = compile(intent); const registry = new KnowledgeSourceRegistry(), retriever = new KnowledgeRetriever(); addEdge(registry, retriever, "fuel-transport", "fuel_price", "causes", "transportation_cost", { domains: ["economics"] }); addEdge(registry, retriever, "transport-operating", "transportation_cost", "causes", "operating_cost", { domains: ["economics"] }); addEdge(registry, retriever, "operating-profit", "operating_cost", "causes", "profit_margin", { domains: ["economics"] }); const result = await new KnowledgeDiscoveryEngine().discover({ projectId: "business", intent, bilContext: compiled.context, sourceRegistry: registry, retriever, relationshipTypeRegistry: compiled.types }); assert.deepEqual(result.rounds.map(({ selectedSourceIds }) => selectedSourceIds), [["fuel-transport"], ["transport-operating"], ["operating-profit"]]); assert.equal(result.sufficiency.status, "sufficient"); assert.ok(result.semanticConceptSet.concepts.some(({ id }) => id === "business")); });

test("no-knowledge, conflict, freshness, access, progress, and artifact budgets stop safely", async () => { const calculation = compile({ rawInput: "Calculate 125 * 48", goal: "Calculate", actions: ["calculate"], context: { domain: "mathematics", expression: "125 * 48" } }); const emptyRegistry = new KnowledgeSourceRegistry(), emptyRetriever = new KnowledgeRetriever(); const none = await new KnowledgeDiscoveryEngine().discover({ projectId: "calc", intent: calculation.context.intent, bilContext: calculation.context, sourceRegistry: emptyRegistry, retriever: emptyRetriever, relationshipTypeRegistry: calculation.types }); assert.equal(none.required, false); assert.equal(none.stopReason, "not_required"); assert.equal(none.artifacts.length, 0);
  const compiled = compile(chainIntent("a", "d")); const conflictRegistry = new KnowledgeSourceRegistry(), conflictRetriever = new KnowledgeRetriever(); for (const [id, value] of [["conflict-a", 100], ["conflict-b", 110]] as const) { const source: KnowledgeSource = { id, name: id, type: "structured", domains: ["test"], conceptIds: ["a", "d"], relationshipTypes: ["causes"], freshness: ["stable"], availability: "available", retrievalKind: "static", provenanceCharacteristics: { traceable: true, evidence: true } }; conflictRegistry.register(source); conflictRetriever.register(new StaticStructuredKnowledgeAdapter(id, { contentType: "structured", concepts: [concept("a"), concept("d")], relationships: [{ id: `${id}-edge`, type: "causes", from: "a", to: "d" }], facts: [{ subject: "a", predicate: "effect", value }], evidence: [{ type: "fixture", value: id }] })); } const conflict = await new KnowledgeDiscoveryEngine().discover({ projectId: "conflict", intent: compiled.context.intent, bilContext: compiled.context, sourceRegistry: conflictRegistry, retriever: conflictRetriever, relationshipTypeRegistry: compiled.types }); assert.equal(conflict.stopReason, "conflicted"); assert.equal(conflict.knowledgeContext.conflicts.length, 1);
  const freshIntent = { ...chainIntent("a", "d"), context: { ...chainIntent("a", "d").context, knowledgeFreshness: "live" } }; const freshCompiled = compile(freshIntent); const stableRegistry = new KnowledgeSourceRegistry(), stableRetriever = new KnowledgeRetriever(); addEdge(stableRegistry, stableRetriever, "stable", "a", "causes", "d"); const fresh = await new KnowledgeDiscoveryEngine().discover({ projectId: "fresh", intent: freshCompiled.context.intent, bilContext: freshCompiled.context, sourceRegistry: stableRegistry, retriever: stableRetriever, relationshipTypeRegistry: freshCompiled.types }); assert.equal(fresh.sufficiency.status, "insufficient"); assert.ok(fresh.gaps.some(({ type }) => type === "freshness_mismatch")); assert.equal(fresh.artifacts.length, 0);
  const privateRegistry = new KnowledgeSourceRegistry(), privateRetriever = new KnowledgeRetriever(); let calls = 0; const privateSource: KnowledgeSource = { id: "private", name: "private", type: "project", domains: ["test"], conceptIds: ["a", "d"], relationshipTypes: ["causes"], freshness: ["stable"], availability: "available", retrievalKind: "static", accessRequirementIds: ["private.read"], provenanceCharacteristics: { traceable: true, evidence: true } }; privateRegistry.register(privateSource); privateRetriever.register({ sourceId: "private", async retrieve(request) { calls++; return new StaticStructuredKnowledgeAdapter("private", { contentType: "graph", concepts: [concept("a"), concept("d")], relationships: [{ id: "private-edge", type: "causes", from: "a", to: "d" }], evidence: [{ type: "private", value: true }] }).retrieve(request); } }); const blocked = await new KnowledgeDiscoveryEngine().discover({ projectId: "private", intent: compiled.context.intent, bilContext: compiled.context, sourceRegistry: privateRegistry, retriever: privateRetriever, relationshipTypeRegistry: compiled.types }); assert.equal(blocked.stopReason, "access_blocked"); assert.equal(calls, 0); const granted = await new KnowledgeDiscoveryEngine().discover({ projectId: "private", intent: compiled.context.intent, bilContext: compiled.context, sourceRegistry: privateRegistry, retriever: privateRetriever, relationshipTypeRegistry: compiled.types, authorizationGrants: [{ id: "grant", requirementId: "private.read", providerId: "private", status: "granted", grantedAt: "1970-01-01T00:00:00.000Z" }] }); assert.equal(granted.stopReason, "sufficient"); assert.equal(calls, 1);
  const artifactBound = await new KnowledgeDiscoveryEngine().discover({ projectId: "bounded", intent: compiled.context.intent, bilContext: compiled.context, sourceRegistry: conflictRegistry, retriever: conflictRetriever, relationshipTypeRegistry: compiled.types, budget: { maxRetrievedArtifacts: 1 } }); assert.equal(artifactBound.stopReason, "budget_exhausted"); assert.ok(artifactBound.artifacts.length <= 1); });

test("discovery results, histories, context identities, and events are deterministic", async () => { const compiled = compile(chainIntent("a", "d")); const registry = new KnowledgeSourceRegistry(), retriever = new KnowledgeRetriever(); addEdge(registry, retriever, "a-b", "a", "causes", "b"); addEdge(registry, retriever, "b-d", "b", "causes", "d"); const run = () => new KnowledgeDiscoveryEngine().discover({ projectId: "deterministic", intent: compiled.context.intent, bilContext: compiled.context, sourceRegistry: registry, retriever, relationshipTypeRegistry: compiled.types }); const left = await run(), right = await run(); assert.equal(left.knowledgeContext.id, right.knowledgeContext.id); assert.deepEqual(left.rounds, right.rounds); assert.deepEqual(left.gaps, right.gaps); assert.deepEqual(left.sufficiency, right.sufficiency); assert.deepEqual(left.events, right.events); });
