"""Generate a browser-viewable trace of actual Python binary execution."""
import base64
import io
import json
from pathlib import Path
import struct
import wave
from core import *


def build_demo():
    samples = [((i % 80)-40)*200 for i in range(1600)]
    pcm = struct.pack('<'+'h'*len(samples),*samples)
    start = BinaryState((Record(1,INT64,struct.pack('<q',3)),Record(2,RGB,bytes([40,80,120])),
        Record(3,UTF8,b'Hi'),Record(4,PCM16,pcm),Record(5,POSITION3,struct.pack('<iii',50,80,0))))
    target = BinaryState((Record(1,INT64,struct.pack('<q',5)),Record(2,RGB,bytes([120,100,80])),
        Record(3,UTF8,b'Hi!'),Record(4,PCM16,struct.pack('<'+'h'*len(samples),*(s*2 for s in samples))),
        Record(5,POSITION3,struct.pack('<iii',180,110,0))))
    instructions = [Instruction(ADD,1,struct.pack('<q',2)),Instruction(COLOR_SHIFT,2,struct.pack('<hhh',80,20,-40)),
        Instruction(APPEND,3,b'!'),Instruction(GAIN,4,struct.pack('<ii',2,1)),Instruction(TRANSLATE,5,struct.pack('<iii',130,30,0))]
    engine = BinaryEngine(instructions)
    result = engine.resolve(start,target,5,10000)
    if not result.accepted: raise RuntimeError(result.reason)
    assert engine.resolve(start,target,5,10000).source == 'memory'
    frames=[]
    labels={ADD:'integer addition',APPEND:'UTF-8 append',COLOR_SHIFT:'RGB channel shift',GAIN:'PCM gain',TRANSLATE:'position translation'}
    for index, raw in enumerate(result.snapshots):
        state=BinaryState.decode(raw); output=decode_outputs(state)
        stream=io.BytesIO()
        with wave.open(stream,'wb') as w:
            w.setnchannels(1);w.setsampwidth(2);w.setframerate(8000);w.writeframes(state.get(4).payload)
        output[4]={'sample_preview':output[4][:16],'wav':'data:audio/wav;base64,'+base64.b64encode(stream.getvalue()).decode()}
        frames.append({'outputs':output,'hex':raw[:120].hex(' '),'bytes':len(raw),
            'operation':'initial state' if index==0 else labels[Instruction.decode(result.program[index-1]).opcode],
            'instruction_hex':'' if index==0 else result.program[index-1].hex(' ')})
    return frames,result

if __name__=='__main__':
    frames,result=build_demo()
    template='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>B-STAE byte-state demo</title>
<style>body{margin:0;background:#101724;color:#e5efff;font:16px system-ui}main{max-width:960px;margin:auto;padding:30px}h1{font-size:30px}section{background:#1c293b;border-radius:12px;padding:20px;margin:16px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px}pre{white-space:pre-wrap;word-break:break-all;font-size:13px;color:#a9cafa}button{padding:10px 16px;border:0;border-radius:8px;cursor:pointer}input{width:100%}.swatch{height:70px;border-radius:8px}svg{background:#101724;width:100%;height:150px}small{color:#9eb0c8}</style>
<main><h1>B-STAE: bytes transform, outputs change</h1><p>This trace was generated by the binary engine. Move through the verified transition path to see the decoded state at each step.</p>
<section><button id="prev">Previous</button> <button id="next">Next</button><p id="step"></p><input aria-label="Transition step" id="slider" type="range" min="0" max="5" value="0"></section>
<div class="grid"><section><h2>Number</h2><p id="number"></p><h2>Text</h2><p id="text"></p></section><section><h2>Color</h2><div class="swatch" id="color"></div><p id="rgb"></p></section><section><h2>Object position</h2><svg viewBox="0 0 300 160"><circle id="object" r="18" fill="#62d4b9"/></svg><p id="position"></p></section></div>
<section><h2>Audio samples</h2><audio id="audio" controls></audio><pre id="samples"></pre><small>Synthetic mono PCM16 waveform, 8 kHz. Gain changes samples; this is audio processing, not speech synthesis.</small></section>
<section><h2>Internal byte state</h2><p id="size"></p><pre id="hex"></pre><h3>Executed instruction bytes</h3><pre id="instruction"></pre><small>Little-endian typed records. State byte preview is truncated to 120 bytes. The final state matches the independently specified target bytes.</small></section>
<p>The search used registered typed operations and full byte-state comparisons. This demo contains no English intent parsing or LLM calls.</p></main>
<script>const frames=FRAMES;let index=0;const el=id=>document.getElementById(id);function render(){const f=frames[index],o=f.outputs;el('slider').value=index;el('step').textContent=`Step ${index} / ${frames.length-1}: ${f.operation}`;el('number').textContent=o[1];el('text').textContent=o[3];el('color').style.background=o[2].hex;el('rgb').textContent=JSON.stringify(o[2]);el('object').setAttribute('cx',o[5][0]);el('object').setAttribute('cy',o[5][1]);el('position').textContent=JSON.stringify(o[5]);el('audio').src=o[4].wav;el('samples').textContent=JSON.stringify(o[4].sample_preview);el('size').textContent=f.bytes+' bytes';el('hex').textContent=f.hex;el('instruction').textContent=f.instruction_hex||'No instruction yet';el('prev').disabled=index===0;el('next').disabled=index===frames.length-1;}el('slider').oninput=e=>{index=Number(e.target.value);render()};el('prev').onclick=()=>{index=Math.max(0,index-1);render()};el('next').onclick=()=>{index=Math.min(frames.length-1,index+1);render()};render();</script></html>'''
    Path(__file__).with_name('byte-demo.html').write_text(template.replace('FRAMES',json.dumps(frames).replace('<','\\u003c')),encoding='utf-8')
    print('Verified binary path:',len(result.program),'operations;',result.expansions,'expanded states')
    print('Created byte-demo.html')
