import { AuthorizationGrant } from "../core/access";
import { RelationshipTypeRegistry } from "../core/relationship.registry";
import { UserIntent } from "../intent/intent.types";
import { BilContext } from "../bil/bil.types";
import { InMemoryExecutionEventLog } from "../execution/event-log";
import { ExecutionEvent } from "../execution/events";
import { KnowledgeContext, normalizeKnowledgeContext } from "./knowledge-context";
import { DiscoveryRound, KnowledgeDiscoveryBudget, KnowledgeDiscoveryStopReason, KnowledgeGap, KnowledgeSufficiencyResult } from "./knowledge-discovery.types";
import { gapsToKnowledgeRequirements, KnowledgeGapDetector } from "./knowledge-gap-detector";
import { resolveKnowledge } from "./knowledge.resolver";
import { KnowledgeRetriever } from "./knowledge-retriever";
import { KnowledgeRequirement } from "./knowledge-requirement.types";
import { KnowledgeSourceRegistry } from "./knowledge-source.registry";
import { KnowledgeArtifact, KnowledgeResolution } from "./knowledge-source.types";
import { ConceptExtractor, SemanticConceptSet, StructuredIntentConceptExtractor } from "./semantic-concepts";
import { DeterministicRelationshipRequirementGenerator, RelationshipExtractor, RelationshipRequirement, RelationshipRequirementGenerator, StructuredArtifactRelationshipExtractor } from "./relationship-discovery";
import { KnowledgeSufficiencyEvaluator } from "./knowledge-sufficiency";

export interface KnowledgeDiscoveryInput { projectId: string; intent: UserIntent; bilContext: BilContext; sourceRegistry: KnowledgeSourceRegistry; retriever: KnowledgeRetriever; relationshipTypeRegistry: RelationshipTypeRegistry; authorizationGrants?: readonly AuthorizationGrant[]; budget?: Partial<KnowledgeDiscoveryBudget>; }
export interface KnowledgeDiscoveryResult { runId: string; required: boolean; semanticConceptSet: SemanticConceptSet; relationshipRequirements: RelationshipRequirement[]; requirements: KnowledgeRequirement[]; generatedRequirements: KnowledgeRequirement[]; artifacts: KnowledgeArtifact[]; gaps: KnowledgeGap[]; rounds: DiscoveryRound[]; stopReason: KnowledgeDiscoveryStopReason; sufficiency: KnowledgeSufficiencyResult; knowledgeContext: KnowledgeContext; events: ExecutionEvent[]; }
const defaults: KnowledgeDiscoveryBudget = { maxRounds: 5, maxGeneratedRequirements: 10, maxRetrievedArtifacts: 25, maxDiscoveredConcepts: 100, maxDiscoveredRelationships: 100 };

export class KnowledgeDiscoveryEngine {
  constructor(private readonly conceptExtractor: ConceptExtractor = new StructuredIntentConceptExtractor(), private readonly requirementGenerator: RelationshipRequirementGenerator = new DeterministicRelationshipRequirementGenerator(), private readonly relationshipExtractor: RelationshipExtractor = new StructuredArtifactRelationshipExtractor(), private readonly gapDetector = new KnowledgeGapDetector(), private readonly sufficiencyEvaluator = new KnowledgeSufficiencyEvaluator()) {}
  async discover(input: KnowledgeDiscoveryInput): Promise<KnowledgeDiscoveryResult> {
    const budget = { ...defaults, ...(input.budget ?? {}) }; validateBudget(budget); const runId = `discovery-${hash(stableStringify({ intent: input.intent, bilContextId: input.bilContext.id, sources: input.sourceRegistry.list(), grants: input.authorizationGrants ?? [], budget }))}`; const log = new InMemoryExecutionEventLog(runId);
    log.append({ type: "knowledge_discovery_started", projectId: input.projectId, data: { bilContextId: input.bilContext.id } }); const semanticConceptSet = this.conceptExtractor.extract(input.intent); log.append({ type: "concept_extraction_completed", projectId: input.projectId, data: { conceptSetId: semanticConceptSet.id, conceptIds: semanticConceptSet.concepts.map(({ id }) => id) } });
    const relationshipRequirements = this.requirementGenerator.generate(input.intent, semanticConceptSet, input.bilContext.knowledgeRequirements, input.relationshipTypeRegistry); for (const relationship of relationshipRequirements) log.append({ type: "relationship_requirement_created", projectId: input.projectId, data: { relationshipRequirementId: relationship.id, from: relationship.from, to: relationship.to } });
    const initial = input.bilContext.knowledgeRequirements.map(({ declaration }) => structuredClone(declaration)); if (!initial.length && relationshipRequirements.length) initial.push(...relationshipRequirements.map((relationship) => ({ id: `knowledge-${relationship.id}`, domain: typeof input.intent.context?.domain === "string" ? input.intent.context.domain : undefined, concepts: [relationship.from, relationship.to], freshness: freshness(input.intent.context?.knowledgeFreshness), requireProvenance: relationship.evidenceRequired, evidenceRequired: relationship.evidenceRequired, required: relationship.required })));
    if (!initial.length && !relationshipRequirements.length) { const resolution = resolveKnowledge([], input.sourceRegistry, { grants: input.authorizationGrants }); const base = normalizeKnowledgeContext(resolution, [], input.relationshipTypeRegistry); const sufficiency = this.sufficiencyEvaluator.evaluate([], []); const context = extend(base, semanticConceptSet, [], [], [], "not_required", sufficiency); log.append({ type: "knowledge_sufficiency_evaluated", projectId: input.projectId, data: { status: sufficiency.status } }); log.append({ type: "knowledge_discovery_completed", projectId: input.projectId, data: { stopReason: "not_required", knowledgeContextId: context.id } }); return { runId, required: false, semanticConceptSet, relationshipRequirements: [], requirements: [], generatedRequirements: [], artifacts: [], gaps: [], rounds: [], stopReason: "not_required", sufficiency, knowledgeContext: context, events: log.list() }; }
    const allRequirements = [...initial], generatedRequirements: KnowledgeRequirement[] = [], artifacts: KnowledgeArtifact[] = [], rounds: DiscoveryRound[] = []; const retrievedSources = new Set<string>(); let active = [...initial], gaps: KnowledgeGap[] = [], stopReason: KnowledgeDiscoveryStopReason = "no_progress", sufficiency: KnowledgeSufficiencyResult = this.sufficiencyEvaluator.evaluate([], []); let context = normalizeKnowledgeContext(resolveKnowledge(initial, input.sourceRegistry, { grants: input.authorizationGrants }), [], input.relationshipTypeRegistry);
    for (let roundNumber = 1; roundNumber <= budget.maxRounds; roundNumber++) {
      log.append({ type: "knowledge_discovery_round_started", projectId: input.projectId, data: { round: roundNumber, requirementIds: active.map(({ id }) => id) } }); const roundResolution = resolveKnowledge(active, input.sourceRegistry, { grants: input.authorizationGrants }); const anchorIds = new Set(active.flatMap(({ concepts }) => concepts.slice(0, 1))); const eligible = roundResolution.entries.flatMap(({ eligibleSourceIds }) => eligibleSourceIds).filter((id, index, values) => values.indexOf(id) === index).filter((id) => !retrievedSources.has(id)).filter((id) => { const source = input.sourceRegistry.get(id)!; return !anchorIds.size || [...anchorIds].some((anchor) => source.conceptIds?.includes(anchor)); }).sort(); const remainingArtifacts = budget.maxRetrievedArtifacts - artifacts.length; const selected = eligible.slice(0, Math.max(0, remainingArtifacts)); const beforeConcepts = new Set(artifacts.flatMap(({ concepts = [] }) => concepts.map(({ id }) => id))), beforeRelationships = new Set(artifacts.flatMap(({ relationships = [] }) => relationships.map(({ id }) => id))), beforeEvidence = artifacts.reduce((sum, artifact) => sum + (artifact.evidence?.length ?? 0), 0); const retrievedThisRound: KnowledgeArtifact[] = [];
      for (const sourceId of selected) { const source = input.sourceRegistry.get(sourceId)!; const requirement = active.find((item) => source.conceptIds?.some((id) => item.concepts.includes(id))) ?? active[0]; const retrievalId = `discovery-retrieval-${hash(`${runId}:${roundNumber}:${requirement.id}:${sourceId}`)}`; const retrieved = await input.retriever.retrieve({ retrievalId, requirement, source, projectContext: input.intent.context }); retrievedSources.add(sourceId); retrievedThisRound.push(...retrieved); }
      const extracted = this.relationshipExtractor.extract(retrievedThisRound, input.relationshipTypeRegistry); const augmented = retrievedThisRound.map((artifact) => ({ ...artifact, relationships: extracted.filter((relationship) => (relationship.metadata?.knowledgeEvidence as { artifactId?: string } | undefined)?.artifactId === artifact.id) })); artifacts.push(...augmented);
      if (new Set(artifacts.flatMap(({ concepts = [] }) => concepts.map(({ id }) => id))).size > budget.maxDiscoveredConcepts || new Set(artifacts.flatMap(({ relationships = [] }) => relationships.map(({ id }) => id))).size > budget.maxDiscoveredRelationships) { artifacts.splice(artifacts.length - augmented.length, augmented.length); stopReason = "budget_exhausted"; break; }
      const fullResolution = resolveKnowledge(allRequirements, input.sourceRegistry, { grants: input.authorizationGrants }); context = normalizeKnowledgeContext(fullResolution, artifacts, input.relationshipTypeRegistry); gaps = this.gapDetector.detect({ requirements: allRequirements, relationshipRequirements, graph: context.graph, context, resolution: fullResolution }); sufficiency = this.sufficiencyEvaluator.evaluate(gaps, context.conflicts); const discoveredConceptIds = context.concepts.map(({ id }) => id).filter((id) => !beforeConcepts.has(id)); const discoveredRelationshipIds = context.relationships.map(({ id }) => id).filter((id) => !beforeRelationships.has(id)); for (const id of discoveredRelationshipIds) log.append({ type: "relationship_discovered", projectId: input.projectId, data: { relationshipId: id, round: roundNumber } }); for (const item of gaps) log.append({ type: "knowledge_gap_detected", projectId: input.projectId, data: { gapId: item.id, type: item.type, round: roundNumber } });
      const room = budget.maxGeneratedRequirements - generatedRequirements.length; const generated = gapsToKnowledgeRequirements(gaps, allRequirements).filter((candidate) => !allRequirements.some((existing) => sameNeed(existing, candidate))).slice(0, Math.max(0, room)); generated.forEach((item) => { generatedRequirements.push(item); allRequirements.push(item); log.append({ type: "followup_knowledge_requirement_created", projectId: input.projectId, data: { requirementId: item.id, round: roundNumber, lineageGapId: item.id.replace(/^followup-/, "") } }); }); const evidenceProgress = artifacts.reduce((sum, artifact) => sum + (artifact.evidence?.length ?? 0), 0) > beforeEvidence; const progress = discoveredConceptIds.length > 0 || discoveredRelationshipIds.length > 0 || evidenceProgress;
      const round: DiscoveryRound = { round: roundNumber, incomingRequirementIds: active.map(({ id }) => id), selectedSourceIds: selected, retrievedArtifactIds: augmented.map(({ id }) => id), discoveredConceptIds, discoveredRelationshipIds, gapIds: gaps.map(({ id }) => id), generatedRequirementIds: generated.map(({ id }) => id), progress, provenance: selected.map((sourceId) => ({ sourceId, artifactIds: augmented.filter((artifact) => artifact.sourceId === sourceId).map(({ id }) => id) })) }; rounds.push(round); log.append({ type: "knowledge_sufficiency_evaluated", projectId: input.projectId, data: { round: roundNumber, status: sufficiency.status } }); log.append({ type: "knowledge_discovery_round_completed", projectId: input.projectId, data: { round: roundNumber, progress, generatedRequirementIds: round.generatedRequirementIds } });
      // A budget stop must win over a sufficiency verdict reached only because the budget starved the
      // round: continuing under a hard bound is not a reason to claim the knowledge is complete.
      if (roundNumber === budget.maxRounds || artifacts.length >= budget.maxRetrievedArtifacts || generatedRequirements.length >= budget.maxGeneratedRequirements) { stopReason = "budget_exhausted"; break; } if (sufficiency.sufficient) { stopReason = "sufficient"; break; } if (sufficiency.status === "conflicted") { stopReason = "conflicted"; break; } if (!gaps.some(({ required }) => required)) { stopReason = "optional_gaps_only"; break; } if (!selected.length) { stopReason = roundResolution.entries.some(({ accessBlockedSourceIds }) => accessBlockedSourceIds.length) ? "access_blocked" : "no_eligible_source"; break; } if (!progress) { stopReason = "no_progress"; break; } active = generated.length ? generated : gapsToKnowledgeRequirements(gaps, allRequirements).slice(0, 1); if (!active.length) { stopReason = "no_eligible_source"; break; }
    }
    const finalContext = extend(context, semanticConceptSet, relationshipRequirements, gaps, rounds, stopReason, sufficiency); log.append({ type: "knowledge_discovery_completed", projectId: input.projectId, data: { stopReason, knowledgeContextId: finalContext.id, rounds: rounds.length } }); return { runId, required: true, semanticConceptSet, relationshipRequirements, requirements: allRequirements, generatedRequirements, artifacts, gaps, rounds, stopReason, sufficiency, knowledgeContext: finalContext, events: log.list() };
  }
}
function extend(base: KnowledgeContext, semanticConceptSet: SemanticConceptSet, relationships: RelationshipRequirement[], gaps: KnowledgeGap[], rounds: DiscoveryRound[], stopReason: KnowledgeDiscoveryStopReason, sufficiency: KnowledgeSufficiencyResult): KnowledgeContext { return deepFreeze({ ...base, id: `knowledge-context-${hash(stableStringify({ baseId: base.id, semanticConceptSet, relationships, gaps, rounds, stopReason, sufficiency }))}`, semanticConceptSet: structuredClone(semanticConceptSet), relationshipRequirements: structuredClone(relationships), gaps: structuredClone(gaps), discoveryRounds: structuredClone(rounds), discoveryStopReason: stopReason, sufficiency: structuredClone(sufficiency) }); }
function sameNeed(left: KnowledgeRequirement, right: KnowledgeRequirement): boolean { return left.freshness === right.freshness && stableStringify([...left.concepts].sort()) === stableStringify([...right.concepts].sort()) && stableStringify([...(left.relationshipTypes ?? [])].sort()) === stableStringify([...(right.relationshipTypes ?? [])].sort()); }
function freshness(value: unknown): KnowledgeRequirement["freshness"] { return ["stable", "recent", "live", "project_current"].includes(String(value)) ? value as KnowledgeRequirement["freshness"] : "stable"; }
function validateBudget(value: KnowledgeDiscoveryBudget): void { for (const [key, amount] of Object.entries(value)) if (!Number.isInteger(amount) || amount < 1) throw new TypeError(`${key} must be a positive integer.`); }
function stableStringify(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${stableStringify(item)}`).join(",")}}`; return JSON.stringify(value); }
function hash(value: string): string { let result = 2166136261; for (let i = 0; i < value.length; i++) { result ^= value.charCodeAt(i); result = Math.imul(result, 16777619); } return (result >>> 0).toString(16).padStart(8, "0"); }
function deepFreeze<T>(value: T): T { if (!value || typeof value !== "object" || Object.isFrozen(value)) return value; if (value.constructor?.name === "BiktingGraph") return value; for (const item of Object.values(value as Record<string, unknown>)) deepFreeze(item); return Object.freeze(value); }
