import { BiktingGraph } from "../core/graph";
import { KnowledgeContext } from "./knowledge-context";
import { KnowledgeGap } from "./knowledge-discovery.types";
import { KnowledgeRequirement } from "./knowledge-requirement.types";
import { KnowledgeResolution } from "./knowledge-source.types";
import { RelationshipRequirement } from "./relationship-discovery";

export interface KnowledgeGapDetectorInput { requirements: readonly KnowledgeRequirement[]; relationshipRequirements: readonly RelationshipRequirement[]; graph: BiktingGraph; context: KnowledgeContext; resolution: KnowledgeResolution; }
export class KnowledgeGapDetector {
  detect(input: KnowledgeGapDetectorInput): KnowledgeGap[] { const gaps: KnowledgeGap[] = [];
    for (const requirement of input.requirements) for (const conceptId of requirement.concepts) if (!input.graph.getEntity(conceptId)) gaps.push(gap("missing_concept", requirement.required, [conceptId], `Concept ${conceptId} has not been discovered.`, requirement.id));
    for (const relationship of input.relationshipRequirements) { const path = findPath(input.graph, relationship.from, relationship.to, relationship.acceptableTypes, relationship.direction === "either"); if (!path.length) { const frontier = reachable(input.graph, relationship.from, relationship.acceptableTypes).at(-1) ?? relationship.from; gaps.push({ ...gap("unresolved_relationship", relationship.required, [frontier, relationship.to], `No supported ${relationship.match} relationship path connects ${relationship.from} to ${relationship.to}.`), relationshipRequirementId: relationship.id, relationshipTypes: relationship.acceptableTypes, frontierConceptId: frontier }); } else if (relationship.evidenceRequired && path.some((edgeId) => !input.graph.getRelationship(edgeId)?.metadata?.knowledgeEvidence)) gaps.push({ ...gap("missing_evidence", relationship.required, [relationship.from, relationship.to], `Relationship ${relationship.id} lacks required evidence.`), relationshipRequirementId: relationship.id, relationshipTypes: relationship.acceptableTypes }); }
    for (const entry of input.resolution.entries) { if (entry.freshnessMismatchSourceIds.length) gaps.push({ ...gap("freshness_mismatch", input.requirements.find(({ id }) => id === entry.requirementId)?.required ?? true, [], `Sources ${entry.freshnessMismatchSourceIds.join(", ")} do not satisfy freshness.`, entry.requirementId), provenance: [{ sourceType: "resolution", sourceId: input.resolution.id }] }); if (entry.uncoveredConceptIds.length || entry.uncoveredRelationshipTypes.length) gaps.push({ ...gap("insufficient_coverage", input.requirements.find(({ id }) => id === entry.requirementId)?.required ?? true, entry.uncoveredConceptIds, "Eligible sources do not collectively cover the requirement.", entry.requirementId), relationshipTypes: entry.uncoveredRelationshipTypes, provenance: [{ sourceType: "resolution", sourceId: input.resolution.id }] }); }
    for (const conflict of input.context.conflicts) gaps.push({ ...gap("conflict", true, [conflict.subject], `Conflicting knowledge remains for ${conflict.subject}.`), provenance: [{ sourceType: "context", sourceId: conflict.id }] });
    return [...new Map(gaps.map((item) => [item.id, item])).values()].sort((a, b) => a.id.localeCompare(b.id)); }
}
export function gapsToKnowledgeRequirements(gaps: readonly KnowledgeGap[], originals: readonly KnowledgeRequirement[]): KnowledgeRequirement[] { return gaps.filter(({ type }) => ["unresolved_relationship", "missing_evidence", "insufficient_coverage"].includes(type)).map((item) => { const original = originals.find(({ id }) => id === item.requirementId) ?? originals.find(({ required }) => required); return { id: `followup-${item.id}`, domain: original?.domain, concepts: [...new Set(item.conceptIds)], topic: item.reason, relationshipTypes: item.type === "insufficient_coverage" ? item.relationshipTypes : undefined, freshness: original?.freshness ?? "stable", minimumAuthority: original?.minimumAuthority, allowedSourceTypes: original?.allowedSourceTypes, accessRequirementIds: original?.accessRequirementIds, requireProvenance: original?.requireProvenance, minimumConfidence: original?.minimumConfidence, evidenceRequired: item.type === "missing_evidence" || original?.evidenceRequired, required: item.required }; }).sort((a, b) => a.id.localeCompare(b.id)); }
function gap(type: KnowledgeGap["type"], required: boolean, conceptIds: string[], reason: string, requirementId?: string): KnowledgeGap { const seed = `${type}:${requirementId ?? ""}:${conceptIds.join(",")}:${reason}`; return { id: `gap-${hash(seed)}`, type, required, requirementId, conceptIds, reason, provenance: [{ sourceType: requirementId ? "bil" : "intent", sourceId: requirementId ?? "intent" }] }; }
function findPath(graph: BiktingGraph, start: string, target: string, types: string[], either: boolean): string[] { if (!graph.getEntity(start) || !graph.getEntity(target)) return []; const queue: Array<{ id: string; edges: string[] }> = [{ id: start, edges: [] }], seen = new Set([start]); while (queue.length) { const current = queue.shift()!; if (current.id === target) return current.edges; const outgoing = graph.getOutgoing(current.id).filter((edge) => !types.length || types.includes(edge.type)); const incoming = either ? graph.getIncoming(current.id).filter((edge) => !types.length || types.includes(edge.type)).map((edge) => ({ ...edge, to: edge.from })) : []; for (const edge of [...outgoing, ...incoming].sort((a, b) => a.id.localeCompare(b.id))) if (!seen.has(edge.to)) { seen.add(edge.to); queue.push({ id: edge.to, edges: [...current.edges, edge.id] }); } } return []; }
function reachable(graph: BiktingGraph, start: string, types: string[]): string[] { if (!graph.getEntity(start)) return []; const ordered: string[] = [], queue = [start], seen = new Set([start]); while (queue.length) { const id = queue.shift()!; ordered.push(id); for (const edge of graph.getOutgoing(id).filter((item) => !types.length || types.includes(item.type)).sort((a, b) => a.id.localeCompare(b.id))) if (!seen.has(edge.to)) { seen.add(edge.to); queue.push(edge.to); } } return ordered; }
function hash(value: string): string { let result = 2166136261; for (let i = 0; i < value.length; i++) { result ^= value.charCodeAt(i); result = Math.imul(result, 16777619); } return (result >>> 0).toString(16).padStart(8, "0"); }
