import { AuthorizationGrant } from "../core/access";
import { KnowledgeRequirement } from "./knowledge-requirement.types";
import { KnowledgeSourceRegistry } from "./knowledge-source.registry";
import { KnowledgeResolution, KnowledgeSource, KnowledgeSourceResolution } from "./knowledge-source.types";

export interface KnowledgeResolutionAccess { grants?: readonly AuthorizationGrant[]; projectContext?: Record<string, unknown>; }
export function resolveKnowledge(requirements: readonly KnowledgeRequirement[], registry: KnowledgeSourceRegistry, access: KnowledgeResolutionAccess = {}): KnowledgeResolution {
  const entries = [...requirements].sort((a, b) => a.id.localeCompare(b.id)).map((requirement): KnowledgeSourceResolution => {
    const domainCompatible = registry.list().filter((source) => baseCompatible(requirement, source)); const freshnessMismatchSourceIds = domainCompatible.filter((source) => !source.freshness.includes(requirement.freshness) && contributes(requirement, source)).map(({ id }) => id); const compatible = domainCompatible.filter((source) => source.freshness.includes(requirement.freshness) && contributes(requirement, source)); const unavailable = compatible.filter(({ availability }) => availability !== "available").map(({ id }) => id); const available = compatible.filter(({ availability }) => availability === "available");
    const blocked = available.filter((source) => !hasAccess(source, requirement, access.grants ?? [])).map(({ id }) => id); const eligible = available.filter((source) => hasAccess(source, requirement, access.grants ?? [])).map(({ id }) => id);
    const incompatible = registry.list().filter((source) => !compatible.includes(source)).map(({ id }) => id); const contributions = compatible.map((source) => ({ sourceId: source.id, coveredConceptIds: requirement.concepts.filter((id) => source.conceptIds?.includes(id)), coveredRelationshipTypes: (requirement.relationshipTypes ?? []).filter((type) => source.relationshipTypes?.includes(type)) })); const eligibleContributions = contributions.filter(({ sourceId }) => eligible.includes(sourceId)); const coveredConcepts = new Set(eligibleContributions.flatMap(({ coveredConceptIds }) => coveredConceptIds)); const coveredRelationships = new Set(eligibleContributions.flatMap(({ coveredRelationshipTypes }) => coveredRelationshipTypes)); const uncoveredConceptIds = requirement.concepts.filter((id) => !coveredConcepts.has(id)); const uncoveredRelationshipTypes = (requirement.relationshipTypes ?? []).filter((type) => !coveredRelationships.has(type)); const unresolved = requirement.required && (!eligible.length || uncoveredConceptIds.length > 0 || uncoveredRelationshipTypes.length > 0);
    const reason = !unresolved ? `${eligible.length} eligible source(s) collectively cover the requirement.` : eligible.length ? "Eligible sources provide only partial collective coverage." : compatible.length ? "Compatible sources exist, but none are available and authorized." : freshnessMismatchSourceIds.length ? "No source satisfies the freshness requirement." : "No source contributes compatible knowledge.";
    return { requirementId: requirement.id, candidateSourceIds: compatible.map(({ id }) => id), eligibleSourceIds: eligible, unavailableSourceIds: unavailable, accessBlockedSourceIds: blocked, incompatibleSourceIds: incompatible, freshnessMismatchSourceIds, contributions, uncoveredConceptIds, uncoveredRelationshipTypes, unresolved, reason, provenance: compatible.map(({ id }) => ({ sourceId: id, reason: eligible.includes(id) ? "eligible" : blocked.includes(id) ? "access_blocked" : "unavailable" })) };
  });
  const normalized = [...requirements].sort((a, b) => a.id.localeCompare(b.id)); return deepFreeze({ id: `knowledge-resolution-${hash(stableStringify({ requirements: normalized, sources: registry.list(), grants: [...(access.grants ?? [])].map(({ id, requirementId, providerId, status }) => ({ id, requirementId, providerId, status })).sort((a, b) => a.id.localeCompare(b.id)) }))}`, requirements: structuredClone(normalized), entries, unresolvedRequirementIds: entries.filter(({ unresolved }) => unresolved).map(({ requirementId }) => requirementId) });
}
function baseCompatible(requirement: KnowledgeRequirement, source: KnowledgeSource): boolean { return (!requirement.domain || source.domains.includes(requirement.domain)) && (!requirement.allowedSourceTypes?.length || requirement.allowedSourceTypes.includes(source.type)) && (requirement.minimumAuthority === undefined || (source.authority?.level ?? 0) >= requirement.minimumAuthority) && (requirement.minimumConfidence === undefined || (source.confidence ?? 0) >= requirement.minimumConfidence) && (!requirement.requireProvenance || source.provenanceCharacteristics?.traceable === true) && (!requirement.evidenceRequired || source.provenanceCharacteristics?.evidence === true); }
function contributes(requirement: KnowledgeRequirement, source: KnowledgeSource): boolean { return (!requirement.concepts.length && !(requirement.relationshipTypes?.length)) || requirement.concepts.some((id) => source.conceptIds?.includes(id)) || (requirement.relationshipTypes ?? []).some((type) => source.relationshipTypes?.includes(type)); }
function hasAccess(source: KnowledgeSource, requirement: KnowledgeRequirement, grants: readonly AuthorizationGrant[]): boolean { const ids = [...new Set([...(source.accessRequirementIds ?? []), ...(requirement.accessRequirementIds ?? [])])]; return ids.every((id) => grants.some((grant) => grant.requirementId === id && grant.providerId === source.id && grant.status === "granted")); }
function stableStringify(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${stableStringify(item)}`).join(",")}}`; return JSON.stringify(value); }
function hash(value: string): string { let result = 2166136261; for (let i = 0; i < value.length; i++) { result ^= value.charCodeAt(i); result = Math.imul(result, 16777619); } return (result >>> 0).toString(16).padStart(8, "0"); }
function deepFreeze<T>(value: T): T { if (!value || typeof value !== "object" || Object.isFrozen(value)) return value; for (const item of Object.values(value as Record<string, unknown>)) deepFreeze(item); return Object.freeze(value); }
